//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a T4 template.
//
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace CoperAlgoLib.Geometry
{
    public struct PointD : IEquatable<PointD>
    {
        public double X;
        public double Y;

        public PointD(double x, double y)
        {
            X = x;
            Y = y;
        }

        public override bool Equals(object obj) => obj is PointD other && Equals(other);

        public override int GetHashCode() => HashCode.Combine(X, Y);

        public bool Equals(PointD other) => X == other.X && Y == other.Y;

        public static bool operator ==(PointD lhs, PointD rhs) => lhs.Equals(rhs);

        public static bool operator !=(PointD lhs, PointD rhs) => !lhs.Equals(rhs);
    }
}
